### ISSUE TITLE
gem install not working

### ISSUE THREAD

**Issue by RonWalker22** [philipqnguyen/cardano_explorer#1]
Hello, 

`gem install` is not working for me. When I followed the install instructions the gem installed fine but I received an error "uninitialized constant CardanoExplorer" when I tried to run my program.  

 I found and opened up the gem's files that were installed locally. I found that they were mostly empty. Seems like when I run `gem install cardano_explorer` I only receive two files, LICENSE.txt & README.md 

I downloaded and added the lib and spec folders as well as the CHANGELOG.md file from here. Now that I have all the files, the error is gone and the gem works fine.

**Comment by philipqnguyen** [comment]
Well that's embarrassing on my part. fixing now =)

**Comment by philipqnguyen** [comment]
@RonWalker22 I just bumped to version 0.1.1 this should fix it.

`gem install cardano_explorer -v '0.1.1' `

You'll probably have to require 'cardano_explorer' in your code as well.

Thanks for reporting this. I literally just published this a few hours ago, going through some initial pains.
