### ISSUE TITLE
address.summary["caBalance"]["getCoin"] disregards the decimal

### ISSUE THREAD

**Issue by RonWalker22** [philipqnguyen/cardano_explorer#2]
While using `address.summary["caBalance"]["getCoin"] ` I found the gem disregards  the decimal when displaying the balance.  

address_1 = DdzFFzCqrhsxGcvRxsWBj7fbSNd7dTAaWzUEeZtNi5qxApPR3EcqEdxcpqrtwPhurhNRurkBDzhBMFPN6W5aPWYCGZG6FpofhBVMwYux

address_2 = DdzFFzCqrhstjNy7BZScomVmJMNbwZsmKtfnncJv6eEgQP49XYbijFTFi4bhBUD5RKSHQ4v5NtMKJhxEdBmeULKxm5jeSbDa6i4fJJHT

---
address_1 has a balance of 4,019.2500  
checked here: https://cardanoexplorer.com/address/DdzFFzCqrhsxGcvRxsWBj7fbSNd7dTAaWzUEeZtNi5qxApPR3EcqEdxcpqrtwPhurhNRurkBDzhBMFPN6W5aPWYCGZG6FpofhBVMwYux

The gem displays 4019250000 for address_1

---

address_2 has a balance of 0.000344
checked here:
https://cardanoexplorer.com/address/DdzFFzCqrhstjNy7BZScomVmJMNbwZsmKtfnncJv6eEgQP49XYbijFTFi4bhBUD5RKSHQ4v5NtMKJhxEdBmeULKxm5jeSbDa6i4fJJHT

The gem displays 344 for address_2

---

**Comment by RonWalker22** [comment]
Sorry, still learning. I read more here: https://cardanodocs.com/cardano/monetary-policy/

The value of "getCoin" is in lovelaces not Ada.

1 ADA = 1,000,000 Lovelaces

**Comment by philipqnguyen** [comment]
@RonWalker22 I was just about to write a response regarding exactly that. Indeed they are in lovelaces. Maybe that should be made clear in the README.md. If you want to make pull request to note that the value is in lovelaces in the README.md, please feel free.
